pipeline:
 - name: "nlp_spacy"
 - name: "tokenizer_spacy"
 - name: "ner_duckling_http"
   dimensions: ["time", "phone-number", "url", "email"]
 - name: "ner_crf"
 - name: "ner_synonyms"
 - name: "intent_featurizer_count_vectors"
 - name: "intent_classifier_tensorflow_embedding"
   intent_tokenization_flag: true
   intent_split_symbol: ","